# Generated by Django 2.0.7 on 2018-07-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_auto_20180731_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
